name: Deploy
on: [push]
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and Build 
        run: |
          npm ci
          npm run build
      - name: Copy 
        run: |
          mkdir site
          cp -r dist site/
          cp -r assets site/
          cp -r plugin site/
          cp index.html site/
          ls site
      - name: Deploy 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: site
          clean: true
          target_folder: ${env.GITHUB_REF_SLUG}
          commit_message: Releasing tag/branch ${env.GITHUB_REF_SLUG}